# Generated by Django 5.2.8 on 2025-11-26 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar_manifest', models.CharField(db_index=True, max_length=100, verbose_name='Numar Manifest')),
                ('numar_permis', models.CharField(blank=True, max_length=100, verbose_name='Numar Permis')),
                ('numar_pozitie', models.CharField(blank=True, max_length=50, verbose_name='Numar Pozitie')),
                ('cerere_operatiune', models.CharField(blank=True, max_length=100, verbose_name='Cerere Operatiune')),
                ('data_inregistrare', models.DateField(blank=True, null=True, verbose_name='Data Inregistrare')),
                ('container', models.CharField(db_index=True, max_length=50, verbose_name='Container')),
                ('numar_colete', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Numar Colete')),
                ('greutate_bruta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Greutate Bruta (kg)')),
                ('descriere_marfa', models.TextField(blank=True, verbose_name='Descriere Marfa')),
                ('nume_nava', models.CharField(blank=True, max_length=200, verbose_name='Nume Nava')),
                ('pavilion_nava', models.CharField(blank=True, max_length=100, verbose_name='Pavilion Nava')),
                ('numar_sumara', models.CharField(blank=True, max_length=100, verbose_name='Numar Sumara')),
                ('tip_container', models.CharField(blank=True, max_length=50, verbose_name='Tip Container')),
                ('linie_maritima', models.CharField(blank=True, max_length=200, verbose_name='Linie Maritima')),
                ('model_container', models.CharField(blank=True, editable=False, max_length=100, verbose_name='Model Container')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
            ],
            options={
                'verbose_name': 'Intrare Manifest',
                'verbose_name_plural': 'Intrari Manifest',
                'ordering': ['-data_inregistrare', '-created_at'],
                'indexes': [models.Index(fields=['numar_manifest', 'container'], name='manifests_m_numar_m_f1b269_idx'), models.Index(fields=['data_inregistrare'], name='manifests_m_data_in_4b1471_idx')],
            },
        ),
    ]
