# Generated by Django 5.2.8 on 2025-11-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestentry',
            name='tip_operatiune',
            field=models.CharField(blank=True, max_length=1, verbose_name='Tip Operatiune'),
        ),
    ]
