# Generated by Django 5.2.8 on 2025-11-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0002_manifestentry_tip_operatiune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestentry',
            name='numar_sumara',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numar Sumara'),
        ),
    ]
