# Generated by Django 5.2.8 on 2025-11-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0003_fix_numar_sumara_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manifestentry',
            options={'ordering': ['numar_curent'], 'verbose_name': 'Intrare Manifest', 'verbose_name_plural': 'Intrari Manifest'},
        ),
        migrations.AddField(
            model_name='manifestentry',
            name='numar_curent',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Numar Curent'),
        ),
        migrations.AddIndex(
            model_name='manifestentry',
            index=models.Index(fields=['numar_curent'], name='manifests_m_numar_c_216534_idx'),
        ),
    ]
