# Generated by Django 5.2.8 on 2025-11-27 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0004_alter_manifestentry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_container', models.CharField(max_length=100, unique=True, verbose_name='Model Container')),
                ('tip_container', models.CharField(max_length=50, verbose_name='Tip Container')),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='container_types/', verbose_name='Imagine Container')),
                ('descriere', models.TextField(blank=True, verbose_name='Descriere')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
            ],
            options={
                'verbose_name': 'Tip Container',
                'verbose_name_plural': 'Tipuri Containere',
                'ordering': ['model_container'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='An')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
            ],
            options={
                'verbose_name': 'An Baza Date',
                'verbose_name_plural': 'Ani Baze Date',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Pavilion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100, unique=True, verbose_name='Nume Pavilion')),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='pavilions/', verbose_name='Imagine Pavilion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
            ],
            options={
                'verbose_name': 'Pavilion',
                'verbose_name_plural': 'Pavilioane',
                'ordering': ['nume'],
            },
        ),
        migrations.AlterModelOptions(
            name='manifestentry',
            options={'ordering': ['numar_curent'], 'verbose_name': 'Intrare Registru Import', 'verbose_name_plural': 'Registru Import 2025'},
        ),
        migrations.AddField(
            model_name='manifestentry',
            name='container_type_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='manifests.containertype', verbose_name='Tip Container (Relatie)'),
        ),
        migrations.AddField(
            model_name='manifestentry',
            name='database_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='manifests.databaseyear', verbose_name='An Baza Date'),
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200, unique=True, verbose_name='Nume Nava')),
                ('linie_maritima', models.CharField(blank=True, max_length=200, verbose_name='Linie Maritima')),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='ships/', verbose_name='Imagine Nava')),
                ('descriere', models.TextField(blank=True, verbose_name='Descriere')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
                ('pavilion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ships', to='manifests.pavilion', verbose_name='Pavilion')),
            ],
            options={
                'verbose_name': 'Nava',
                'verbose_name_plural': 'Nave',
                'ordering': ['nume'],
            },
        ),
        migrations.AddField(
            model_name='manifestentry',
            name='ship_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='manifests.ship', verbose_name='Nava (Relatie)'),
        ),
    ]
