# Generated by Django 5.2.8 on 2025-11-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0005_containertype_databaseyear_pavilion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manifestentry',
            options={'ordering': ['numar_curent'], 'verbose_name': 'Intrare Registru Import', 'verbose_name_plural': 'Registru import RE1'},
        ),
        migrations.AddField(
            model_name='pavilion',
            name='nume_tara',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nume Țară'),
        ),
    ]
