# Generated by Django 5.2.8 on 2025-11-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0006_alter_manifestentry_options_pavilion_nume_tara'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200, unique=True, verbose_name='Nume Template')),
                ('descriere', models.TextField(blank=True, verbose_name='Descriere')),
                ('rand_start', models.IntegerField(default=2, help_text='Primul rând cu date (nu header)', verbose_name='Rând de început')),
                ('format_fisier', models.CharField(choices=[('xls', 'XLS'), ('xlsx', 'XLSX')], default='xlsx', max_length=10, verbose_name='Format Fișier')),
                ('mapare_coloane', models.JSONField(default=dict, help_text='Ex: {"numar_manifest": "numar manifest", "container": "container"}', verbose_name='Mapare Coloane')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
            ],
            options={
                'verbose_name': 'Template Import',
                'verbose_name_plural': 'Template-uri Import',
                'ordering': ['nume'],
            },
        ),
        migrations.AlterModelOptions(
            name='manifestentry',
            options={'ordering': ['numar_curent'], 'verbose_name': 'Intrare Registru Import', 'verbose_name_plural': 'Registru Import 2025'},
        ),
    ]
