# Generated by Django 5.2.8 on 2025-11-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0007_importtemplate_alter_manifestentry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestentry',
            name='observatii',
            field=models.TextField(blank=True, verbose_name='Observatii'),
        ),
    ]
